build:
  nodes:
    my-tests:
      environment:
        php:
          version: 8.1
                        
filter:
    excluded_paths: [vendor/*, tests/*]
checks:
    php:
        code_rating: true
        duplication: true
tools:
    external_code_coverage: true
