name: Codecov

on:
  push:
    branches: [ main ]

jobs:
  codecov: 
    runs-on: ubuntu-latest
    steps:
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
