name: Codecov

on:
  push:
    branches: [ main ]

jobs:
  codecov: 
    runs-on: ubuntu-latest
    steps:
      - name: Install PHP 
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.1'
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run test suite
        run: vendor/bin/phpunit
      - uses: actions/checkout@master
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: "./phpunit.cache/code-coverage"
