name: 'Split packages'

on:
  push:
    branches: [ main ]
    tags: '*'

env:
    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    
jobs:
  split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - path: 'Config'
            repo: 'config'
            
          - path: 'Container'
            repo: 'config'
            
          - path: 'Contract'
            repo: 'contract'
            
          - path: 'Event'
            repo: 'event'
            
          - path: 'Helper'
            repo: 'helper'
            
          - path: 'Http'
            repo: 'http'
            
          - path: 'Kernel'
            repo: 'Kernel'
            
          - path: 'Provider'
            repo: 'Provider'
            
          - path: 'Routing'
            repo: 'routing'
            
          - path: 'Server'
            repo: 'server'
            
          - path: 'Validation'
            repo: 'validation'

    steps:
      - uses: actions/checkout@v2
      - uses: "symplify/monorepo-split-github-action@2.1"
        with:
          package_directory: 'src/${{ matrix.path }}'
          repository_organization: 'nyxio-php'
          repository_name: '${{ matrix.repo }}'
          user_name: "nyxio-php-split"
          user_email: "action@github.com"
