name: Split

on:
  push:
    branches: [ main ]
    tags: '*'
    
env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    
jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path: 'Config'
            split_repository: 'config'
            
          - local_path: 'Container'
            split_repository: 'config'
            
          - local_path: 'Contract'
            split_repository: 'contract'
            
          - local_path: 'Event'
            split_repository: 'event'
            
          - local_path: 'Helper'
            split_repository: 'helper'
            
          - local_path: 'Http'
            split_repository: 'http'
            
          - local_path: 'Kernel'
            split_repository: 'Kernel'
            
          - local_path: 'Provider'
            split_repository: 'Provider'
            
          - local_path: 'Routing'
            split_repository: 'routing'
            
          - local_path: 'Server'
            split_repository: 'server'
            
          - local_path: 'Validation'
            split_repository: 'validation'

    steps:
      - uses: actions/checkout@v2
      - uses: "symplify/monorepo-split-github-action@2.1"
        with:
            package_directory: 'src/${{ matrix.package.local_path }}'

            repository_organization: 'nyxio-php'
            repository_name: '${{ matrix.package.split_repository }}'

            repository_host: github.com
            #user_name: "nyxio-ci"
            #user_email: "dev@nyxio-framework.com"
            user_name: "ishutin"
            user_email: "ishutin.alexey@gmail.com"
