name: 'Update'

on:
  push:
    branches: [ main ]
    tags: '*'

jobs:
  split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - path: 'Config'
            repo: 'config'

          - path: 'Container'
            repo: 'config'

          - path: 'Contract'
            repo: 'contract'

          - path: 'Event'
            repo: 'event'

          - path: 'Helper'
            repo: 'helper'

          - path: 'Http'
            repo: 'http'

          - path: 'Kernel'
            repo: 'Kernel'

          - path: 'Provider'
            repo: 'Provider'

          - path: 'Routing'
            repo: 'routing'

          - path: 'Server'
            repo: 'server'

          - path: 'Validation'
            repo: 'validation'

    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: "src/${{ matrix.path }}"
          # Host
          repository_host: "github.com"
          # Remote organization
          repository_organization: "nyxio-php"
          # Remote repository
          repository_name: "${{ matrix.repo }}"
          # Git branch
          branch: "main"
          # Git User Email
          user_name: 'kaizen-ci'
          user_email: 'info@kaizen-ci.org'
