name: 'Update'

on:
  push:
    branches: [ main ]
    tags: '*'

jobs:
  split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - path: 'Config'
            repo: 'config'

          - path: 'Container'
            repo: 'config'

          - path: 'Contract'
            repo: 'contract'

          - path: 'Event'
            repo: 'event'

          - path: 'Helper'
            repo: 'helper'

          - path: 'Http'
            repo: 'http'

          - path: 'Kernel'
            repo: 'Kernel'

          - path: 'Provider'
            repo: 'Provider'

          - path: 'Routing'
            repo: 'routing'

          - path: 'Server'
            repo: 'server'

          - path: 'Validation'
            repo: 'validation'

    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          run: |
            mkdir temp
            cd temp
            git clone https://github.com/nyxio-php/${{ matrix.repo }}.git
            rsync ../src/${{ matrix.path }} /${{ matrix.repo }}
            cd ${{ matrix.repo }}
            git add .
            git commit -m 'sync'
            git push
            
